server.port=8080
server.address=0.0.0.0
server.forward-headers-strategy=framework
spring.profiles.active=test
spring.application.name=viviendaSmart-backend

# Variables preparadas para Railway o Localhost
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/viviendaSmart?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring Data JPA Configuration
spring.jpa.show-sql=true

# Spring Data JPA Hibernate Configuration
# CAMBIO A CREATE PARA GENERAR TODAS LAS TABLAS (Recuerda regresarlo a update después)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.firststudent.platform.viviendasmartbackend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days = 7

# CORS Configuration
# REMOTO
spring.graphql.cors.allowed-origins=https://purple-river-0ad475110.7.azurestaticapps.net, https://front-opensource.web.app
# LOCAL
# spring.graphql.cors.allowed-origins=https://front-opensource.web.app
spring.graphql.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

# Corrección: Se separó la línea de allowed-origins y allow-credentials
spring.graphql.cors.allowed-origins=https://purple-river-production.up.railway.app, https://front-opensource-production.up.railway.app, https://viviendasmart-frontend-production.up.railway.app
spring.graphql.cors.allow-credentials=true
